version: "3.8"

networks:
  web:

services:
  nginx:
    image: nginx:stable-alpine
    container_name: saas_nginx
    ports:
      - "8002:80"
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql
      - redis
    networks:
      - web

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: saas_php
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    ports:
      - "9000:9000"
    environment:
      - COMPOSER_MEMORY_LIMIT=-1
    networks:
      - web
    depends_on:
      - mysql
      - redis

  mysql:
      image: mysql:8.0
      container_name: saas_mysql
      environment:
          MYSQL_ROOT_PASSWORD: rootpassword
          MYSQL_DATABASE: caravea
          MYSQL_USER: user
          MYSQL_PASSWORD: caraveapassword
      volumes:
          - mysql_data:/var/lib/mysql
      networks:
          - web
      ports:
          - "3307:3306"

  redis:
    image: redis:alpine
    container_name: saas_redis
    restart: unless-stopped
    tty: true
    ports:
      - "6379:6379"
    volumes:
      - ./docker/redis:/var/lib/redis
    networks:
      - web

volumes:
  mysql_data:
